export { default as AbsentRequest } from './AbsentRequest';
export {default as Consultation} from './Consultation';
export {default as Dashboard} from './Dashboard';
export {default as Patients} from './Patients';
export {default as PatientDetails} from './PatientDetails';
export {default as Appointments} from './Appointments';
export {default as Inventory} from './Inventory';
export {default as Dispensary} from './Dispensary';
export {default as Login} from './Login';
export {default as PatientSearchResults} from './PatientSearchResults';
